repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-symlinks
      - id: destroyed-symlinks # It doesn't work (the way I thought it'd be, maybe.)
      - id: check-case-conflict
      - id: check-added-large-files
  - repo: https://github.com/nrbnlulu/qt-hooks
    rev: v0.1.5
    hooks:
      - id: qml-format
        files: |
            (?x)^(
                systems/programming/qt/
            )$
