name = input('Input Your Name: ')
age = input('Input Your age: ')
print('Your name is ' + name + ' and your age is ' + age)
print('and also your name is ' + name + ' and your age is' , age)
ageger = int(age)
print('once again, your name is ' + name + ' and also your age is' , ageger)